// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package model

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        int64            `json:"id"`
	Email     string           `json:"email"`
	Weight    int16            `json:"weight"`
	Height    int16            `json:"height"`
	BirthDate pgtype.Date      `json:"birth_date"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
