version: "3.9"
services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=dhack
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - dhack-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=debug
      - SERVER_ADDRESS=:8080
      - DB_SOURCE=postgresql://postgres:root@postgres:5432/dhack
    depends_on:
      - postgres
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--" ]
    command: [ "/app/main" ]
    networks:
      - dhack-network

networks:
  dhack-network:
    driver: bridge