CREATE TABLE users (
  id BIGSERIAL PRIMARY KEY, 
  email VARCHAR(100) NOT NULL, 
  weight SMALLINT NOT NULL, 
  height SMALLINT NOT NULL, 
  birth_date DATE NOT NULL, 
  created_at TIMESTAMP NOT NULL DEFAULT(now())
);